### ISSUE TITLE
2019 版更新反馈

### ISSUE THREAD

**Issue by Ovilia** [Ovilia/ovilia.github.io#10]
在这里留下你的反馈吧~

**Comment by willin** [comment]
火钳刘明。要不是没在意鼠标拖拽了一下，就不知道有下一页。

**Comment by tim-hub** [comment]
cannot believe it you seriously upgrade it.

**Comment by simon300000** [comment]
好看！

**Comment by Ovilia** [comment]
@simon300000 有道理，可以改进一下~

**Comment by kalasoo** [comment]
很赞，设计上很有感觉。微信聊天这里我几乎测试了每一个组合，赞

**Comment by Ovilia** [comment]
@kalasoo d=====(￣▽￣*)b厉害

**Comment by SpaceBoundR** [comment]
这个风格太棒了吧！

**Comment by Ovilia** [comment]
@SpaceBoundR 谢谢！

**Comment by tim-hub** [comment]
is the previous version still alive?

**Comment by Ovilia** [comment]
@tim-hub Yes. From http://zhangwenli.com/2017 to http://zhangwenli.com/2013

**Comment by sauchye** [comment]
So cool ~ 😎

**Comment by tnjin** [comment]
赞一下，很酷

**Comment by wangjuye** [comment]
口红色号  真的是多

**Comment by hfqq** [comment]
水球图点击后一直没反应

**Comment by Ovilia** [comment]
@60m 应该会链接到 https://ecomfe.github.io/echarts-liquidfill/example/ 为什么没反应呢？控制台有报错吗？

**Comment by 60m** [comment]
重新测试了一下，上面链接单独打开没问题，但速度略慢，可能需要加载资源，但是在你的页面中点击水球图按钮后，等待超过30s也没反应（测试均在安卓手机完成），换了一台安卓手机也是，使用电脑点击后响应速度比较长，等一会可以打开。估计和你链接的页面有关系

**Comment by Ovilia** [comment]
@60m 嗯，这个链接是 GitHub 的

**Comment by joshua19881228** [comment]
很棒的个人网站！读你的博客，我反而不是一种读技术博客的感觉（可能是因为我不懂前端技术orz），更像是在读一个人的心路历程，也让我在创业的苦逼生活中，重新燃起了对技术的热情。加油~~

**Comment by Ovilia** [comment]
@joshua19881228 感谢，加油~

**Comment by ClareChu** [comment]
小姐姐，很强啊！ 希望像小姐姐学习，哈哈

**Comment by liubiantao** [comment]
![image](https://user-images.githubusercontent.com/3268218/64149457-85dfee80-ce58-11e9-8eaf-7050a8775241.png)
书籍推荐有个bug，说话的人反了

**Comment by Ovilia** [comment]
@liubiantao 谢谢反馈！

**Comment by salvan13** [comment]
nice web site :D

**Comment by Ovilia** [comment]
@salvan13 Glad you like it! XD

**Comment by mattlin4567** [comment]
太神啦

**Comment by silverriver** [comment]
膜拜前端大神

**Comment by isgbuddy** [comment]
头像是你本人吗？好清新啊

**Comment by SidVal** [comment]
Love your web.

Good job ! :heart:

**Comment by Ovilia** [comment]
Thank you all! 😍

**Comment by dmwin72015** [comment]
确实很有创意，很漂亮！但是看起来总感觉很变扭，或许是我老了吧！

**Comment by YuunYang** [comment]
之前可以很方便找到blog入口，可是现在找了好久都找不到呀

**Comment by YuunYang** [comment]
and `手机` 滑动的时候有点点生硬噢

PS，做为之前给小姐姐写过email还收到过回信的人，今天居然发现bilibili也开了，果断关注

**Comment by Ovilia** [comment]
@YuunYang 信息反馈~

**Comment by xuvlog** [comment]
小姐姐居然放照片啦，很漂亮！祝生活幸福哦～

**Comment by cmpute** [comment]
太牛逼了。。。过来膜拜一下！

**Comment by geekyouth** [comment]
很有创意，赞

**Comment by FanyangMengDev** [comment]
啊啊啊啊啊超爱小姐姐这个网站风格啊！太棒了吧！女神！

**Comment by Ovilia** [comment]
谢谢~~

**Comment by jsu93** [comment]
心灵手巧人美 点个赞 

keep going~~

**Comment by xumengzi** [comment]
![WeChat](https://user-images.githubusercontent.com/15715076/70791491-2a67ba00-1dd2-11ea-8da4-8d052c46d9e8.png)
微信聊天里面有bug, 那个回答应该是你回答的

**Comment by Ovilia** [comment]
@xumengzi 谢谢反馈

**Comment by sxy7990** [comment]
太喜欢这个风格了！

**Comment by Pontuer** [comment]
> 在这里留下你的反馈吧~

你好，这个风格很喜欢，我现在也有在倒腾自己的个人网站，不知道可以使用你的主题代码吗？因为这个比较私人，所以得得到你的允许

**Comment by Ovilia** [comment]
@Pontuer 可以

**Comment by Alex-Cin** [comment]
堂姐, 你好啊...

**Comment by Guochengjie** [comment]
巨佬的每一个版本的主页都好好看，orz

**Comment by 2220209876** [comment]
有没有计划增加主题模式？
现在的模式像是夜间模式

**Comment by tomhaitao** [comment]
为什么现在echarts官网找不到社区了呢

**Comment by thjiang** [comment]
https证书挂了

**Comment by Ovilia** [comment]
@thjiang 其实没有配置 https……我晚点检查下，谢谢！

**Comment by VT-Tony** [comment]
有创意

**Comment by xch900910** [comment]
nice website

**Comment by dannyxu2015** [comment]
Issue机器人的页面链接404了：https://github.com/Ovilia/echarts-robot

**Comment by jiangwanqiang** [comment]
口红色号可视化希望可以支持搜索,还可以延伸出商城链接,恰饭后门+1 ,(doge

**Comment by angxuejian** [comment]
真的好酷。喜欢

**Comment by yixuanzhe** [comment]
nice

**Comment by AndSpark** [comment]
小姐姐的想法太棒了，点个赞

**Comment by tizee** [comment]
很棒的交互！感动ing。

**Comment by 983579869** [comment]
赞、赞、赞。真是在最对的时间看见对的风格！大爱

**Comment by webxmsj** [comment]
聊天这角度介绍自己蛮有意思的， 呵呵

**Comment by lizheng-31** [comment]
封控在家无聊，尝试做了个 “借助阿里物联网的温度描画微信小程序”，从ec组件摸索到这里，设计大师啊👍。冒个泡，感谢下！

**Comment by ruivers** [comment]
我轻轻的来了 ，踩了踩，嗯 感觉是不是得留下什么，于是我写下齐天大圣到此一游

**Comment by XuanmoFeng** [comment]
活钱流氓

**Comment by HowieHz** [comment]
很酷的博客

**Comment by doraemonxxx** [comment]
`awsome website`

**Comment by suisuiz** [comment]
太优秀啦，向大佬学习

**Comment by jianglin-code** [comment]
surprise!

**Comment by DeividCurcio** [comment]
Top parabéns

**Comment by shaishab316** [comment]
Hi there, we have been so surprised seeing you github and works.

**Comment by DeividCurcio** [comment]
Bom dia recebi o e-mail de vcs e queria saber mais sobre a empresa e como
posso estar trabalhando junto ?

Meu whatsapp+5522999604947

Em seg., 13 de abr. de 2026, 03:01, Shaishab Chandra Shil <
***@***.***> escreveu:
