### ISSUE TITLE
在user列表返回xianzhe列表的时候会出问题

### ISSUE THREAD

**Issue by liangbijie** [Ovilia/ovilia.github.io#5]
`
appendDialog(id) {

                if (typeof id === 'object' && id.length > 0) {
                    // array of dialog ids
                    id.forEach(id => this.appendDialog(id));
                    return;
                }

                else if (id == null) {
                    this.lastDialog = null;
                    // bug!!
                    // this.lastDialog.responses = null;
                    return;

                }

                this.isXianzheTyping = true;
                const dialog = this.getDialog(id);
                getRandomMsg(dialog.details)
                    .forEach(content => {
                        this.msgChain = this.msgChain
                            .then(() => delay(700))
                            .then(() => this.sendMsg(content, AUTHOR.XIANZHE));
                    });

                return dialog.nextXianzhe
                    ? this.appendDialog(dialog.nextXianzhe)
                    : this.msgChain.then(() => {
                        this.lastDialog = dialog;
                        this.isXianzheTyping = false;
                    });
            },

            sendMsg(message, author) {
                switch (author) {
                    case 'me':
                        return this.sendUserMsg(message);
                    default:
                        return this.sendFriendMsg(message, author);
                }
            }, `

this.lastDialog.responses = null  这行会把原始数据修改，导致返回xianzhe列表异常

**Comment by Ovilia** [comment]
谢谢，如何复现？

**Comment by liangbijie** [comment]
从某一个xiezhe对象跳到user列表里面，然后再调回这个xiezhe对象，就会出现xiezhe对象里面response为null

**Comment by Ovilia** [comment]
更新了一版，应该不存在这个问题了。
